include: "rules/00_common.smk"

##### Target rules #####

rule all:
    input:
#####################
# 01_pre-processing
#####################
# copy_videos
        expand(os.path.join(config["working_dir"], "raw_videos/{sample}.avi"),
                sample = samples["sample"]
        ),
# set_split_coords
        expand("results/split_coord_images/{sample}.png",
                sample = samples["sample"]
        ),

#####################

##### Modules #####

include: "rules/01_pre-processing.smk"
