####################
# Config files
####################
samples_file:
    config/samples.csv
samples_long:
    config/samples_long.csv
excluded_videos:
    config/tracking_fails.csv
####################
# Parameters
####################
seconds_interval:
    - 0.05
    - 0.08
    - 0.1
    - 0.15
    - 0.2
    - 0.3
    - 0.5
    - 1
####################
# Locations
####################
repo_dir:
    /hps/software/users/birney/ian/repos/MIKK_F0_tracking
raw_data_dir:
    /nfs/ftp/private/indigene_ftp/upload/behaviour/transfer/20191111_panel_1/all_to_analyse
working_dir:
    /hps/nobackup/birney/users/ian/MIKK_F0_tracking
data_store_dir:
    /nfs/research/birney/projects/indigene/MIKK_F0_tracking
tmpdir:
    /hps/nobackup/birney/users/ian/tmp
shared_dir:
    /hps/nobackup/birney/users/ian/MIKK_all
####################
# Containers
####################
opencv:
    /hps/nobackup/birney/users/ian/containers/MIKK_F0_tracking/opencv_4.5.1.sif
idtrackerai:
    # NOTE: Dockerfile for this container: workflow/envs/idtrackerai/Dockerfile
    docker://saulpierottiebi/idtrackerai_cpu_gui:latest
rocker_tidyverse:
    docker://rocker/tidyverse:4.1.2
R_4.2.0:
    /hps/nobackup/birney/users/ian/containers/MIKK_F0_tracking/R_4.2.0.sif

