####################
# Config files
####################
samples_file:
    config/samples.csv
excluded_videos:
    config/tracking_fails.csv
####################
# Parameters
####################

####################
# Locations
####################
repo_dir:
    /hps/software/users/birney/ian/repos/MIKK_F0_tracking
raw_data_dir:
    /nfs/ftp/private/indigene_ftp/upload/behaviour/transfer/20191111_panel_1/all_to_analyse
working_dir:
    /hps/nobackup/birney/users/ian/MIKK_F0_tracking
data_store_dir:
    /nfs/research/birney/projects/indigene/MIKK_F0_tracking
####################
# Containers
####################
opencv:
    /hps/nobackup/birney/users/ian/containers/MIKK_F0_tracking/opencv_4.5.1.sif
idtrackerai:
    # NOTE: Dockerfile for this container: workflow/envs/idtrackerai/Dockerfile
    docker://saulpierottiebi/idtrackerai_cpu_gui:latest



